### ISSUE TITLE
Consolidate CSS styles

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#105]
Currently, many CSS styles used in our app are not stored in the associated CSS files for the pages/components to which the styles are applied. For example, a header class style can be found in the nearly every Page's CSS file instead of the appropriate Header.css file. As these styles affect the Header component, the Header.css file is where they should live. This has also caused a lot of redundant code, as most headers are given a unique class name even though the styles are the same for almost every header instance. These classes can be consolidated into one class in the respective component's CSS file (e.g., for this example, Header.css).

### Tasks:

- [ ] Move styles for each page/component to the associated CSS files
- [ ] Consolidate redundant styles into the same style/class (see list of files below)
- [x] Convert class names to use a variation of BEM formatting:
  - `block__element modifierA modifierB`

### Files:

**Note:** This list is not complete! Please verify all CSS files, including those not in this list, are not currently storing styles for pages/components other than the associated page/component

- [ ] **Header.css (headers)** <-- Target file where styles should be written (classes that should be moved here)
  - [ ] Favorites/Bookmarks <-- Files where applicable styles are inappropriately placed
  - [ ] Home
  - [ ] Login
  - [ ] Password Reset
  - [ ] Popular
  - [ ] Reviews
  - [ ] Search
  - [ ] Signup
- [ ] **index.css (body)**
  - [ ] Favorites/Bookmarks
  - [ ] Home
  - [ ] HomePageHeader
  - [ ] Login
  - [ ] Password Reset
  - [ ] Popular
  - [ ] Reviews
  - [ ] Search
  - [ ] Signup
  - [ ] Navbar
- [ ] **App.css (form, etc.)**
  - [ ] Login
  - [ ] Password Reset
  - [ ] Signup
- [ ] **Button.css (button, logout, settings, backButton, etc.)**
  - [ ] HomePageHeader
  - [ ] Settings
